### ISSUE TITLE
software-station freezes after opening on "syncing packages data"

### ISSUE THREAD

**Issue by nevillehay** [ghostbsd/software-station#1]
terminal output from starting software-station as root
# software-station

(software-station:77505): Gtk-WARNING **: 21:35:44.015: Locale not supported by C library.
	Using the fallback 'C' locale.
Error creating proxy: The connection is closed (g-io-error-quark, 18)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.6/site-packages/software_station-0.1-py3.6.egg/EGG-INFO/scripts/software-station", line 279, in initial_sync
  File "/usr/local/lib/python3.6/site-packages/software_station-0.1-py3.6.egg/EGG-INFO/scripts/software-station", line 265, in sync_packages
  File "/usr/local/lib/python3.6/site-packages/software_station-0.1-py3.6.egg/software_station.py", line 43, in available_package_dictionary
    pkg_list = available_package_list()
  File "/usr/local/lib/python3.6/site-packages/software_station-0.1-py3.6.egg/software_station.py", line 19, in available_package_list
    lst = list(set(pkg_out.stdout.read().splitlines()))
  File "/usr/local/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2255497: ordinal not in range(128)

**Comment by ericbsd** [comment]
fixed in https://github.com/ghostbsd/software-station/commit/cad404d624d956ba4d344927632b748712fe538b
