### ISSUE TITLE
When you start Software-station you will be logged out

### ISSUE THREAD

**Issue by wintstar** [ghostbsd/software-station#37]
,        ,            root@xxxx-ghostbsd 
            /(        )`           --------------------- 
            \ \___   / |           OS: GhostBSD 24.01.1 amd64 
            /- _  `-/  '           Kernel: 14.0-STABLE 
           (/\/ \ \   /\           Uptime: 25 mins 
           / /   | `    \          Packages: 730 (pkg) 
           O O   ) /    |          Shell: fish 3.6.1 
           `-^--'`<     '          Terminal: mate-terminal 
          (_.)  _  )   /           CPU: Intel Core 2 Duo P8600 (2) @ 2.394GHz 
           `.___/`    /            GPU: Mobile 4 Series Chipset Integrated Grap 
             `-----' /             Memory: 2595MiB / 5987MiB 
<----.     __ / __   \
<----|====O)))==) \) /====|                                
<----'    `--' `.__,' \                                    
             |        |
              \       /       /\
         ______( (_  / \______/
       ,'  ,-----'   |
       `--{__________)

After installing packages in the software station, it no longer starts. When you click on the 'Software station' menu button, the screen goes black and the login mask appears. This came after the recent GhostBSD system updates. I then reinstalled GhostBSD and did not install the latest system update. And the same error occurred.

This is output in the terminal as root. 

```
software-station
Traceback (most recent call last):
  File "/usr/local/bin/software-station", line 953, in <module>
    TableWindow()
  File "/usr/local/bin/software-station", line 76, in __init__
    Gtk.Window.__init__(self)
  File "/usr/local/lib/python3.9/site-packages/gi/overrides/Gtk.py", line 519, in __init__
    raise RuntimeError(
RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.
```

**Comment by wintstar** [comment]
I have found the source of the error. If I activate the Vimix-Light theme, then there is this error in the backup, update and software station.

**Comment by ericbsd** [comment]
@wintstar For that information it is useful.
